# Generated by Django 6.0.5 on 2026-05-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_task_created_by_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MPESA', 'MPESA')], max_length=50),
        ),
    ]
